create table person(
                       id int generated by default as identity primary key ,
                       full_name varchar (100) UNIQUE NOT NULL,
                       year int check ( year>1900));

insert into  person (full_name, year) VALUES ('Афиногенов Бека Махмудович ',1999);

create table book(
                     id int generated by default as identity primary key ,
                     owner_id int references person(id) on delete set null,
                     title varchar (100) unique not null ,
                     author varchar(100) not null ,
                     year_of_release int  check (year_of_release > 1500 and year_of_release < 2023)
);

insert into book (owner_id, title, author, year_of_release) VALUES (1,'Мы','Марк Твен',2022);